[[pages]]
path = "filters.py"
name = "Streamlit-Vizzu"
icon = "🏠"

[[pages]]
path = "1-tutorial.py"
name = "Tutorial Example"
icon = "📚"

[[pages]]
path = "pages/3-drilldown.py"
name = "Drilldown"
icon = "🔍"

[[pages]]
path = "pages/5-complex_explorer.py"
name = "Complex Explorer"
icon = "🗺️"